name: Build and Deploy Docs

on:
 push:
   branches:
     - master
 pull_request:

jobs:
 build-docs:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: 3.11

     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install -r docs/source/requirements.txt

     - name: Build documentation
       run: |
         cd docs
         make html

     - name: Trigger ReadTheDocs Build
       uses: dfm/rtds-action@v1
       with:
         webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
         webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
         commit_ref: ${{ github.ref }}

